[project]
name = "parse_gam"
version = "0.1.0"
description = "Parse Backgammon state from video."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "geopandas>=1.1.1",
    "matplotlib>=3.10.7",
    "numpy>=2.3.3",
    "shapely>=2.1.2",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.214",
    "Pillow",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
parse-yolo-predictions = "parse_gam.scripts.parse_prediction:main"
visualize-state = "parse_gam.scripts.visualize_state:main"
smooth-frame-predictions = "parse_gam.scripts.smooth_frame_predictions:main"
detect-moves = "parse_gam.scripts.detect_moves:main"
extract-die-crops = "parse_gam.scripts.extract_die_crops:main"
extract-cube-crops = "parse_gam.scripts.extract_cube_crops:main"
parse-game = "parse_gam.scripts.parse_game:main"
parse-gam = "parse_gam.scripts.run_pipeline:main"
